changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 💅🏾 Features & Enhancement
      labels:
        - feature/enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: ♻️ Changes and Refactors
      labels:
        - refactor/chore
    - title: 🌎 Other Changes
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
